version: '3.3'
services:
  app:
    build: .
    volumes:
      - ./applogs:/applogs
      - type: bind
        source: ./google_cloud_credentials.json
        target: /app/creds/google_cloud_credentials.json
      - type: bind
        source: ./src/config.cfg
        target: /app/src/config.cfg

volumes:
  applogs:
